kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-created-persistent-volume-claim 
spec:
  storageClassName: pv-demo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi

